# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi


echo "*************************************************************"

/usr/bin/uptime

echo "*************************************************************"

echo "This System is running on  " 

cat /etc/redhat-release


echo "*************************************************************"

