---
- hosts: localhost
  tasks:
    - name: start dock
      block:
        - set_fact:
            containerName: "dock_ksam-{{ 999 | random }}" 

        - include_role:
            name: ci

- hosts: docker_host
  tasks:
    - include_role:
       name: test_temp


- hosts: localhost
  tasks:
    - include_role:
       name: destroy_container