---
- set_fact:
    containerName: "dock_ksam-{{ 999 | random }}" 

- name: "pull docker image"
  shell: "docker pull {{ dock_img }}"

- name: "start container"
  shell: "docker run -d -it --name {{ containerName }} {{ dock_img }} /bin/bash"

- name: "add container to inventory"
  add_host:
    name: "docker_host"
    ansible_host: "{{ containerName }}"
    ansible_connection: docker
    ansible_user: root
    
