---
- set_fact:
    containerName: "dock_ksam-{{ 999 | random }}" 

#pulling image from docker hub
- name: "pull docker image"
  shell: "docker pull {{ dock_img }}" 

- name: "start container"
  shell: "docker run -d -it -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN -p 80:80 --name {{ containerName }} {{ dock_img }}"
# Fixed d-bus-connection-operation-not-permitted error
- name: "add container to inventory"
  add_host:
    name: "docker_host"
    ansible_host: "{{ containerName }}"
    ansible_connection: docker
    ansible_user: root
    
